"""empty message

<<<<<<<< HEAD:migrations/versions/c9998768607b_.py
Revision ID: c9998768607b
Revises: 
Create Date: 2023-11-05 20:55:18.152768
========
Revision ID: fff5f932bb13
Revises: 
Create Date: 2023-11-05 18:07:30.408318
>>>>>>>> dev:migrations/versions/fff5f932bb13_.py

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/c9998768607b_.py
revision = 'c9998768607b'
========
revision = 'fff5f932bb13'
>>>>>>>> dev:migrations/versions/fff5f932bb13_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('instagram', sa.String(length=50), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('car_type', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_type'], ['car_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('times', sa.String(length=50), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
<<<<<<<< HEAD:migrations/versions/c9998768607b_.py
========
    sa.Column('car', sa.String(length=50), nullable=False),
>>>>>>>> dev:migrations/versions/fff5f932bb13_.py
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE car_types SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE services SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE bookings SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('bookings')
    op.drop_table('services')
    op.drop_table('users')
    op.drop_table('car_types')
    # ### end Alembic commands ###
